In [1]:
import pandas as pd
import numpy as np

**1. Pandas version**

In [5]:
pd.__version__

'2.0.3'

**2. Load csv into dataframe and count columns**

In [2]:
df = pd.read_csv ('data/housing.csv')
df.shape

(20640, 10)

**3. Find columns with null values**

In [7]:
nan_count = df.isna().sum()
print(nan_count)

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64


**4. Unique values for ocean_proximity**

In [8]:
df['ocean_proximity'].unique().size

5

**5. Average value of the 'median_house_value' for the houses near the bay**

In [23]:
rslt_df = df[df['ocean_proximity'] == 'NEAR BAY']
rslt_df['median_house_value'].mean()

259212.31179039303

In [24]:
df['median_house_value'][df['ocean_proximity'] == 'NEAR BAY'].mean()

259212.31179039303

**6. Has the mean value changed after filling missing values?**

In [35]:
avg = df['total_bedrooms'].mean()
print(avg)

537.8705525375617


In [30]:
df['total_bedrooms'] = df['total_bedrooms'].fillna(avg)

537.8705525375617


In [ ]:
avg = df['total_bedrooms'].mean()
print(avg)

In [34]:
nan_count = df.isna().sum()
print(nan_count)

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64


**7: Value of the last element of w\***

In [7]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [19]:
X = df[['housing_median_age','total_rooms','total_bedrooms']][df['ocean_proximity'] == 'ISLAND'].to_numpy()
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [71]:
XTX = X.T @ X
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [72]:
# alternate calculation
np.dot(np.transpose(X),X)

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [73]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [74]:
np.dot(np.linalg.inv(XTX), XTX)

array([[ 1.00000000e+00,  4.92762949e-13,  1.25374971e-13],
       [-4.39833716e-16,  1.00000000e+00, -1.66300350e-15],
       [ 1.04674299e-15,  1.09601998e-14,  1.00000000e+00]])

In [75]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [76]:
w = (XTX_inv @ X.T) @ y
w

array([23.12330961, -1.48124183,  5.69922946])

In [67]:
# alternate calculation
np.dot(np.dot(np.linalg.inv(np.dot(X.T,X)),X.T),y)

array([23.12330961, -1.48124183,  5.69922946])